exports.kmapid_fixtures = [
    {type: "places", id: "places-8483", name: ""},
    {type: "places", id: "places-637", name: "Lhasa"},
    {type: "places", id: "places-22675", name: ""},
    {type: "places", id: "places-22471" , name: ""},
    {type: "subjects", id: "subjects-6403", name: "Tibet and Himalayas"},
    {type: "subjects", id: "subjects-2328", name: "By pupose to be achieved"},
    {type: "subjects", id: "subjects-829", name: ""},
    {type: "places", id: "places-13656", name: "United States of America"},
    {type: "places", id: "places-13736", name: ""},
    {type: "places", id: "places-433", name: "Sera Monastery"},
    {type: "places", id: "places-434", name: ""},
    {type: "places", id: "places-2", name: "Tibet Autonomous Region"},
    {type: "places", id: "places-435", name: ""},
];